package UI_Admin;

import Logic.entity.Phim;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PV
 */
public class EditFilm extends javax.swing.JFrame {
    private int selectedRow;
    private DefaultTableModel model;
    /**
     * Creates new form EditFilm
     */
    public EditFilm() {
        initComponents();
    }
    public EditFilm(int selectedRow,DefaultTableModel model){
        this.selectedRow = selectedRow;
        this.model = model;
        initComponents();
        loadFilmData();
    }
    
    private void loadFilmData() {
        txtFilmID.setText(model.getValueAt(selectedRow, 0).toString());
        txtFilmName.setText(model.getValueAt(selectedRow, 1).toString());
        txtFilmTG.setText(model.getValueAt(selectedRow, 2).toString());
        txtFilmTL.setText(model.getValueAt(selectedRow, 4).toString());
        txtFilmLang.setText(model.getValueAt(selectedRow, 5).toString());
        txtFilmActor.setText(model.getValueAt(selectedRow, 6).toString());
        txtFilmDes.setText(model.getValueAt(selectedRow, 7).toString());
        txtFilmAnh.setText(model.getValueAt(selectedRow, 8).toString());

        String idPhim = txtFilmID.getText().trim();
        Connection conn = DBConnection.KetNoi();
        String sql = """
                        SELECT tenTheLoai 
                        FROM phim_theLoai pt 
                        JOIN the_loai tl ON pt.idTheLoai = tl.idTheLoai 
                        WHERE idPhim = ?
                    """;
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPhim);
            ResultSet rs = ps.executeQuery();
            List<String> theLoaiList = new ArrayList<>();
            while (rs.next()) {
                theLoaiList.add(rs.getString("tenTheLoai"));
            }
            ckbCoTrang.setSelected(theLoaiList.contains("Cổ trang - Thần thoại"));
            ckbFunny.setSelected(theLoaiList.contains("Hài hước"));
            ckbHorror.setSelected(theLoaiList.contains("Kinh dị - Ma"));
            ckbFamily.setSelected(theLoaiList.contains("Gia đình - Học đường"));
            ckbHoatHinh.setSelected(theLoaiList.contains("Hoạt hình"));
            ckbTamLy.setSelected(theLoaiList.contains("Tâm lý - Tình cảm"));
            conn.close();
        } catch (SQLException e) {
            System.out.println("Lỗi tải thể loại: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFilmID2 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFilmID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFilmName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFilmTG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFilmActor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFilmTL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFilmLang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFilmDes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        ckbCoTrang = new javax.swing.JCheckBox();
        ckbFunny = new javax.swing.JCheckBox();
        ckbHorror = new javax.swing.JCheckBox();
        ckbTamLy = new javax.swing.JCheckBox();
        ckbHoatHinh = new javax.swing.JCheckBox();
        ckbFamily = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        txtFilmAnh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA THÔNG TIN PHIM");

        jLabel2.setText("Mã phim:");

        jLabel3.setText("Tên phim:");

        jLabel4.setText("Tác giả:");

        jLabel5.setText("Diễn viên:");

        jLabel6.setText("Thời lượng:");

        txtFilmTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilmTLActionPerformed(evt);
            }
        });

        jLabel7.setText("Thể loại:");

        jLabel9.setText("Ngôn ngữ:");

        jLabel10.setText("Mô tả:");

        txtFilmDes.setColumns(20);
        txtFilmDes.setRows(5);
        txtFilmDes.setMaximumSize(new java.awt.Dimension(212, 150));
        jScrollPane1.setViewportView(txtFilmDes);

        jLabel11.setText("Ảnh:");

        ckbCoTrang.setText("Cổ trang - Thần thoại");

        ckbFunny.setText("Hài hước");

        ckbHorror.setText("Kinh dị - Ma");

        ckbTamLy.setText("Tâm lý - Tình cảm");

        ckbHoatHinh.setText("Hoạt hình");

        ckbFamily.setText("Gia đình - Học đường");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFilmAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtFilmAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbFunny, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbHorror, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbCoTrang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbHoatHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbFamily)
                            .addComponent(ckbTamLy))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFilmTG)
                                    .addComponent(txtFilmName)
                                    .addComponent(txtFilmID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel11)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFilmActor)
                                    .addComponent(txtFilmLang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFilmTL)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFilmID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFilmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFilmTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbCoTrang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbFunny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbHorror))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbFamily)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbHoatHinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ckbTamLy)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFilmTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFilmLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFilmActor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(69, 69, 69))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilmTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilmTLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilmTLActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String idPhim = txtFilmID.getText().trim();
        String tenPhim = txtFilmName.getText().trim();
        String tacGia = txtFilmTG.getText().trim();
        String thoiLuong = txtFilmTL.getText().trim();
        String ngonNgu = txtFilmLang.getText().trim();
        String dienVien = txtFilmActor.getText().trim();
        String moTa = txtFilmDes.getText().trim();
        String anhPhim = txtFilmAnh.getText().trim();

        
        // Lấy danh sách thể loại từ checkbox
        List<String> theLoaiList = new ArrayList<>();
        if (ckbCoTrang.isSelected()) theLoaiList.add("Cổ trang - Thần thoại");
        if (ckbFunny.isSelected())    theLoaiList.add("Hài hước");
        if (ckbHorror.isSelected())   theLoaiList.add("Kinh dị - Ma");
        if (ckbFamily.isSelected())   theLoaiList.add("Gia đình - Học đường");
        if (ckbHoatHinh.isSelected()) theLoaiList.add("Hoạt hình");
        if (ckbTamLy.isSelected())    theLoaiList.add("Tâm lý - Tình cảm");

        // Kiểm tra dữ liệu đầu vào
        if (idPhim.isEmpty() || tenPhim.isEmpty() || tacGia.isEmpty() || theLoaiList.isEmpty() ||
            thoiLuong.isEmpty() || ngonNgu.isEmpty() || dienVien.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin bắt buộc!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
if (!tacGia.matches("[\\p{L}\\s,]+")) {
            JOptionPane.showMessageDialog(this, "Tên tác giả không được chứa kí tự đặc biệt hoặc số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!ngonNgu.matches("[\\p{L}\\s,]+")){
            JOptionPane.showMessageDialog(this, "Ngôn ngữ không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!dienVien.matches("[\\p{L}\\s,]+")) {
            JOptionPane.showMessageDialog(this, "Tên diễn viên không được chứa số hoặc ký tự đặc biệt!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Tạo đối tượng Phim
        Phim phim = new Phim(idPhim, tenPhim, tacGia, theLoaiList, thoiLuong, ngonNgu, dienVien, moTa, anhPhim);

        // Cập nhật phim
        if (PhimDAO.capNhatPhim(phim)) {
            JOptionPane.showMessageDialog(this, "Cập nhật phim thành công!");
            model.setValueAt(idPhim, selectedRow, 0);
            model.setValueAt(tenPhim, selectedRow, 1);
            model.setValueAt(tacGia, selectedRow, 2);
            model.setValueAt(String.join(", ", theLoaiList), selectedRow, 3);
            model.setValueAt(thoiLuong, selectedRow, 4);
            model.setValueAt(ngonNgu, selectedRow, 5);
            model.setValueAt(dienVien, selectedRow, 6);
            model.setValueAt(moTa, selectedRow, 7);
            model.setValueAt(anhPhim, selectedRow, 8);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật phim thất bại!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox ckbCoTrang;
    private javax.swing.JCheckBox ckbFamily;
    private javax.swing.JCheckBox ckbFunny;
    private javax.swing.JCheckBox ckbHoatHinh;
    private javax.swing.JCheckBox ckbHorror;
    private javax.swing.JCheckBox ckbTamLy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFilmActor;
    private javax.swing.JTextField txtFilmAnh;
    private javax.swing.JTextArea txtFilmDes;
    private javax.swing.JTextField txtFilmID;
    private javax.swing.JTextField txtFilmID2;
    private javax.swing.JTextField txtFilmLang;
    private javax.swing.JTextField txtFilmName;
    private javax.swing.JTextField txtFilmTG;
    private javax.swing.JTextField txtFilmTL;
    // End of variables declaration//GEN-END:variables
}
